// <auto-generated />
using CineReviewP2.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineReviewP2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("CineReviewP2.Models.Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MidiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MidiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("CineReviewP2.Models.Midia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMidia")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Midias");

                    b.HasDiscriminator<string>("TipoMidia").HasValue("Midia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CineReviewP2.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MidiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MidiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("CineReviewP2.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CineReviewP2.Models.Filme", b =>
                {
                    b.HasBaseType("CineReviewP2.Models.Midia");

                    b.Property<int>("DuracaoEmMinutos")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Filme");
                });

            modelBuilder.Entity("CineReviewP2.Models.Serie", b =>
                {
                    b.HasBaseType("CineReviewP2.Models.Midia");

                    b.Property<int>("Temporadas")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Serie");
                });

            modelBuilder.Entity("CineReviewP2.Models.Favorito", b =>
                {
                    b.HasOne("CineReviewP2.Models.Midia", "Midia")
                        .WithMany("Favoritos")
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineReviewP2.Models.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CineReviewP2.Models.Nota", b =>
                {
                    b.HasOne("CineReviewP2.Models.Midia", "Midia")
                        .WithMany("Notas")
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineReviewP2.Models.Usuario", "Usuario")
                        .WithMany("Notas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CineReviewP2.Models.Midia", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("CineReviewP2.Models.Usuario", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
